Comienzo de un EDA preeliminar

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [5]:
dfDevices = pd.read_csv('devices-1681209661.csv', encoding='latin-1')
dfEvents = pd.read_csv('events-1681209680.csv', encoding='latin-1')
dfManufacturers = pd.read_csv('manufacturers-1681209657.csv', encoding='latin-1')

C:\Users\arizo\AppData\Local\Temp\ipykernel_20144\3345008901.py:2: DtypeWarning: Columns (0: action_level, 1: create_date, 2: date_updated, 3: determined_cause, 4: number, 5: target_audience) have mixed types. Specify dtype option on import or set low_memory=False.
  dfEvents = pd.read_csv('events-1681209680.csv', encoding='latin-1')

In [4]:
dfDevices.head()

,id,classification,code,description,distributed_to,implanted,name,number,quantity_in_commerce,risk_class,slug,country,manufacturer_id,created_at,updated_at
0,1,NaN,NaN,IVD Other,NaN,NaN,Cell-Dyn Emerald Cleanser,NaN,NaN,NaN,tur-cell-dyn-emerald-cleanser,TUR,1,2022-08-04 08:28:00 UTC,2022-08-04 08:28:00 UTC
1,2,NaN,NaN,Class IIB,NaN,NaN,"TECNIS Monofocal 1-piece, TECNIS 1-Piece IOL w...",NaN,NaN,NaN,tur-tecnis-monofocal-1-piece-tecnis-1-piece-io...,TUR,2,2022-08-04 08:28:00 UTC,2022-08-04 08:28:00 UTC
2,3,NaN,NaN,Class IIA,NaN,NaN,Centurion FMS Package for Centurion Vision System,NaN,NaN,NaN,tur-centurion-fms-package-for-centurion-vision...,TUR,3,2022-08-04 08:28:00 UTC,2022-08-04 08:28:00 UTC
3,4,NaN,NaN,Class IIB,NaN,NaN,Focusforce intraocular foldable lenses,NaN,NaN,NaN,tur-focusforce-intraocular-foldable-lenses,TUR,4,2022-08-04 08:28:00 UTC,2022-08-04 08:28:00 UTC
4,5,NaN,NaN,IVD Other,NaN,NaN,Cholesterol HDL Direct,NaN,NaN,NaN,tur-cholesterol-hdl-direct,TUR,5,2022-08-04 08:28:00 UTC,2022-08-04 08:28:00 UTC

In [6]:
dfEvents.head()

,id,action,action_classification,action_level,action_summary,authorities_link,country,create_date,data_notes,date,...,status,target_audience,type,uid,uid_hash,url,slug,device_id,created_at,updated_at
0,1,NaN,NaN,NaN,Recall,https://www.titck.gov.tr/,TUR,NaN,NaN,2016-04-04,...,NaN,NaN,Field Safety Notice,2016/294 & FA24MAR2016,41570514,https://web.archive.org/web/20170817053524/htt...,tur-cell-dyn-emerald-cleanser,1,2022-08-04 08:28:00 UTC,2022-08-04 08:28:00 UTC
1,2,NaN,NaN,NaN,Recall,https://www.titck.gov.tr/,TUR,NaN,NaN,2016-09-20,...,NaN,NaN,Field Safety Notice,2016/844 & FSCA2016-02,415f04f4,https://web.archive.org/web/20170817104322/htt...,tur-tecnis-monofocal-1-piece-tecnis-1-piece-io...,2,2022-08-04 08:28:00 UTC,2022-08-04 08:28:00 UTC
2,3,NaN,NaN,NaN,Recall,https://www.titck.gov.tr/,TUR,NaN,NaN,2016-05-09,...,NaN,NaN,Field Safety Notice,2016/437 & 2016018,2caa03df,https://web.archive.org/web/20170818050616/htt...,tur-centurion-fms-package-for-centurion-vision...,3,2022-08-04 08:28:00 UTC,2022-08-04 08:28:00 UTC
3,4,NaN,NaN,NaN,Recall,https://www.titck.gov.tr/,TUR,NaN,NaN,2016-12-19,...,NaN,NaN,Field Safety Notice,2016/1188 & 002/AS60130/17.00,666f0625,https://web.archive.org/web/20171014025042/htt...,tur-focusforce-intraocular-foldable-lenses,4,2022-08-04 08:28:00 UTC,2022-08-04 08:28:00 UTC
4,5,NaN,NaN,NaN,Recall,https://www.titck.gov.tr/,TUR,NaN,NaN,2017-02-20,...,NaN,NaN,Field Safety Notice,2017/242 & 02R06-21 / 02R06-31,6a8d063c,https://web.archive.org/web/20171014000531/htt...,tur-cholesterol-hdl-direct,5,2022-08-04 08:28:00 UTC,2022-08-04 08:28:00 UTC

In [ ]:
dfDevices.columns

In [ ]:
transactions = dfDevices.groupby('Type').sum()

In [ ]:
transactions.columns

In [ ]:
print(transactions.head(20))